packages:
  # Below: where the packages are
  - 'packages/*'
  - 'sites/*'
  # Below excludes are only for Turbo because it doesn't respect gitignore like pnpm does
  - '!packages/example-to-exclude'
