// Generated by astro-build-time-constants

export const digits2 = (number: number) => number < 10 ? '0' + number : '' + number
export const astroBuildTimeConstants = {
  internal: {
    epoch: 1784798186,
    seconds: 26,
    minutes: 16,
    hours: 11,
    fullYear: 2026,
    month: 7,
    date: 23,
    iso: "2026-07-23T09:16:26.293Z",
  },
  custom: {
    "version": {
      "splide": "2.1.1",
      "swiper": "2.7.1",
      "lightgallery": "2.6.0",
      "leaflet": "1.11.0",
      "webtools": "1.2.0",
      "buildtimecontants": "1.0.1"
    }
  },
}
