// Generated by astro-build-time-constants

export const digits2 = (number: number) => number < 10 ? '0' + number : '' + number
export const astroBuildTimeConstants = {
  internal: {
    epoch: 1790164709,
    seconds: 29,
    minutes: 58,
    hours: 13,
    fullYear: 2026,
    month: 9,
    date: 23,
    iso: "2026-09-23T11:58:29.430Z",
  },
  custom: {
    "version": {
      "flag": "1.0.0",
      "splide": "2.1.1",
      "swiper": "2.10.0",
      "lightgallery": "2.6.0",
      "leaflet": "1.11.0",
      "webtools": "1.2.0",
      "buildtimecontants": "1.0.1"
    }
  },
}
