// Generated by astro-build-time-constants

export const digits2 = (number: number) => number < 10 ? '0' + number : '' + number
export const astroBuildTimeConstants = {
  internal: {
    epoch: 1782664835,
    seconds: 35,
    minutes: 40,
    hours: 18,
    fullYear: 2026,
    month: 6,
    date: 28,
    iso: "2026-06-28T16:40:35.115Z",
  },
  custom: {
    "version": {
      "splide": "2.1.1",
      "swiper": "2.7.1",
      "lightgallery": "2.6.0",
      "leaflet": "1.11.0",
      "webtools": "1.2.0",
      "buildtimecontants": "1.0.1"
    }
  },
}
