name: Deploy to GitHub Pages

on:
  # Trigger the workflow every time you push to the `main` branch
  # Using a different branch name? Replace `main` with your branch’s name
  # push:
  #   branches: [main]
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

# Allow this job to clone the repo and create a page deployment
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v5
      - name: Install, build, and upload your site output
        uses: pascal-brand38/action@v1
        with:
            path: .
            package-manager: pnpm@latest
            # node-version: 20 # The specific version of Node that should be used to build your site. Defaults to 18. (optional)
            # package-manager: npm@latest # The Node package manager that should be used to install dependencies and build your site. Automatically detected based on your lockfile. (optional)

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  linkChecker:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download build
        uses: actions/download-artifact@v4
        with:
          name: github-pages
          path: dist/

      - name: Create a dist with astro-dev inside to reflect base which is astro-dev
        run: |
          mkdir dist-local
          cp -r dist dist-local/astro-dev
          cd dist-local/astro-dev
          tar -xvf artifact.tar
          cd ../..

      - name: Restore lychee cache
        uses: actions/cache@v4
        with:
          path: .lycheecache
          key: cache-lychee-${{ github.sha }}
          restore-keys: cache-lychee-

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v2
        with:
          # 403 means it fails because the server detected it was a bot
          # --accept 200..=206,403 to accept 2xx and 403 responses as provided in https://github.com/lycheeverse/lychee/issues/1157
          args: "--insecure --root-dir ${{ github.workspace }}/dist-local --exclude 'astro-dev/404' --cache --max-cache-age 1d 'dist-local/**/*.html' --accept 200..=206,403"
          fail: false

      # - name: Create Issue From File
      #   if: steps.lychee.outputs.exit_code != 0
      #   uses: peter-evans/create-issue-from-file@v5
      #   with:
      #     title: Link Checker Report
      #     content-filepath: ./lychee/out.md
      #     labels: report, automated issue

      - name: Fail if broken links found
        if: steps.lychee.outputs.exit_code != 0
        run: |
          echo "Link checker found broken links."
          exit 1

  buildNpm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v5
      - name: Install, build, and upload your site output
        uses: pascal-brand38/action@v1
        with:
            path: .
            package-manager: npm@latest
            artifact-name: npm-build
            # node-version: 20 # The specific version of Node that should be used to build your site. Defaults to 18. (optional)

  # buildYarn:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout your repository using git
  #       uses: actions/checkout@v5
  #     - name: Install, build, and upload your site output
  #       uses: withastro/action@v5
  #       with:
  #           path: .
  #           package-manager: yarn@latest
  #           # node-version: 20 # The specific version of Node that should be used to build your site. Defaults to 18. (optional)
  #           # package-manager: npm@latest # The Node package manager that should be used to install dependencies and build your site. Automatically detected based on your lockfile. (optional)

  # buildBun:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout your repository using git
  #       uses: actions/checkout@v5
  #     - name: Install, build, and upload your site output
  #       uses: withastro/action@v5
  #       with:
  #           path: .
  #           package-manager: bun@latest
  #           # node-version: 20 # The specific version of Node that should be used to build your site. Defaults to 18. (optional)
  #           # package-manager: npm@latest # The Node package manager that should be used to install dependencies and build your site. Automatically detected based on your lockfile. (optional)

  # Deno is not supported yet by astro from out-of-the-box
  # buildDeno:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout your repository using git
  #       uses: actions/checkout@v5
  #     - name: Install, build, and upload your site output
  #       uses: withastro/action@v5
  #       with:
  #           path: .
  #           package-manager: deno@latest
  #           # node-version: 20 # The specific version of Node that should be used to build your site. Defaults to 18. (optional)
  #           # package-manager: npm@latest # The Node package manager that should be used to install dependencies and build your site. Automatically detected based on your lockfile. (optional)
