name: Lychee Link Checker

on:
  # Trigger the workflow every time you push to the `main` branch
  # Using a different branch name? Replace `main` with your branch’s name
  # push:
  #   branches: [main]
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

# Allow this job to clone the repo and create a page deployment
permissions:
  contents: read
  pages: write
  id-token: write
  issues: write # required for peter-evans/create-issue-from-file

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v5
      - name: Install, build, and upload your site output
        uses: withastro/action@v2
        with:
            path: .
            # node-version: 20 # The specific version of Node that should be used to build your site. Defaults to 18. (optional)
            # package-manager: npm@latest # The Node package manager that should be used to install dependencies and build your site. Automatically detected based on your lockfile. (optional)

      - name: Restore lychee cache
        uses: actions/cache@v4
        with:
          path: .lycheecache
          key: cache-lychee-${{ github.sha }}
          restore-keys: cache-lychee-

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v2
        with:
          # 403 means it fails because the server detected it was a bot
          # --accept 200..=206,403 to accept 2xx and 403 responses as provided in https://github.com/lycheeverse/lychee/issues/1157
          args: "--root-dir ${{ github.workspace }}/dist --cache --max-cache-age 1d 'dist/**/*.html' --accept 200..=206,403"
          fail: false

      - name: Create Issue From File
        if: steps.lychee.outputs.exit_code != 0
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          labels: report, automated issue

      - name: Fail if broken links found
        if: steps.lychee.outputs.exit_code != 0
        run: |
          echo "Link checker found broken links."
          exit 1
